# Generated by Django 5.0.1 on 2024-01-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest',
            name='images',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
